<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'title' => 'QuickTapp Mobile App',
                'category' => 'Mobile App',
                'image' => 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80',
                'description' => 'A fast on-demand mobile app for tapping and ordering services with a streamlined UX.',
                'link' => '#',
                'tags' => ['Flutter', 'Laravel', 'REST'],
                'seo_title' => 'QuickTapp Mobile App',
                'seo_description' => 'On-demand mobile app with seamless ordering and tracking.',
                'seo_keywords' => 'quicktapp, mobile app, on-demand',
                'focus_keyword' => 'QuickTapp',
            ],
            [
                'title' => 'Restaurant Booking System',
                'category' => 'Restaurant',
                'image' => 'https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Table reservations, waitlist management, and notifications for restaurants.',
                'link' => '#',
                'tags' => ['Laravel', 'Livewire', 'Tailwind'],
                'seo_title' => 'Restaurant Booking System',
                'seo_description' => 'Restaurant table booking and waitlist system.',
                'seo_keywords' => 'restaurant booking, reservations',
                'focus_keyword' => 'Restaurant Booking',
            ],
            [
                'title' => 'Tour & Travel Booking Platform',
                'category' => 'Travel',
                'image' => 'https://images.unsplash.com/photo-1502920917128-1aa500764b0e?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Tours, itineraries, packages, and secure payments for travel agencies.',
                'link' => '#',
                'tags' => ['Laravel', 'Stripe', 'Alpine.js'],
                'seo_title' => 'Tour and Travel Booking',
                'seo_description' => 'Complete tour booking platform with itineraries.',
                'seo_keywords' => 'tour booking, travel packages',
                'focus_keyword' => 'Travel Booking',
            ],
            [
                'title' => 'Content Management System (CMS)',
                'category' => 'CMS',
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Flexible CMS with page builder, roles and permissions.',
                'link' => '#',
                'tags' => ['Laravel', 'Spatie Permissions', 'Tailwind'],
                'seo_title' => 'CMS Platform',
                'seo_description' => 'Modern CMS with role-based access and page builder.',
                'seo_keywords' => 'cms, content management',
                'focus_keyword' => 'CMS',
            ],
            [
                'title' => 'Customer Relationship Management (CRM)',
                'category' => 'CRM',
                'image' => 'https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Lead tracking, pipelines, activities, and analytics for sales teams.',
                'link' => '#',
                'tags' => ['Laravel', 'MySQL', 'Charts'],
                'seo_title' => 'CRM System',
                'seo_description' => 'CRM with pipelines and customer lifecycle analytics.',
                'seo_keywords' => 'crm, leads, sales',
                'focus_keyword' => 'CRM',
            ],
            [
                'title' => 'Transport Management System (TMS)',
                'category' => 'Logistics',
                'image' => 'https://images.unsplash.com/photo-1544829099-2911a6ce7023?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Fleet, shipments, routes, and delivery tracking for logistics.',
                'link' => '#',
                'tags' => ['Laravel', 'Maps API', 'Redis'],
                'seo_title' => 'TMS Logistics',
                'seo_description' => 'Transport management system with route and fleet tracking.',
                'seo_keywords' => 'tms, logistics, transport',
                'focus_keyword' => 'TMS',
            ],
            [
                'title' => 'E-Commerce Storefront',
                'category' => 'E-Commerce',
                'image' => 'https://images.unsplash.com/photo-1519336555923-59661f41bb45?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Storefront with catalog, cart, checkout, and order management.',
                'link' => '#',
                'tags' => ['Laravel', 'Stripe', 'Tailwind'],
                'seo_title' => 'E-Commerce Storefront',
                'seo_description' => 'Modern e-commerce storefront with secure checkout.',
                'seo_keywords' => 'ecommerce, storefront, checkout',
                'focus_keyword' => 'Storefront',
            ],
            [
                'title' => 'Hotel Management System',
                'category' => 'Hospitality',
                'image' => 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Rooms, bookings, billing, and guest management.',
                'link' => '#',
                'tags' => ['Laravel', 'MySQL', 'Tailwind'],
                'seo_title' => 'Hotel Management',
                'seo_description' => 'Hotel booking and guest management portal.',
                'seo_keywords' => 'hotel, booking, hospitality',
                'focus_keyword' => 'Hotel Management',
            ],
            [
                'title' => 'Event Ticketing Platform',
                'category' => 'Events',
                'image' => 'https://images.unsplash.com/photo-1508704019882-f9cf40e475b4?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Event listings, ticket sales, QR validation at entry.',
                'link' => '#',
                'tags' => ['Laravel', 'QR', 'Tailwind'],
                'seo_title' => 'Event Ticketing',
                'seo_description' => 'Ticketing platform with secure QR validation.',
                'seo_keywords' => 'events, ticketing, qr',
                'focus_keyword' => 'Ticketing',
            ],
            [
                'title' => 'HR Management System (HRMS)',
                'category' => 'HR',
                'image' => 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Employees, attendance, payroll, and performance tracking.',
                'link' => '#',
                'tags' => ['Laravel', 'MySQL', 'Tailwind'],
                'seo_title' => 'HRMS',
                'seo_description' => 'HR management with attendance and payroll.',
                'seo_keywords' => 'hr, payroll, attendance',
                'focus_keyword' => 'HRMS',
            ],
            [
                'title' => 'Inventory Management Portal',
                'category' => 'ERP',
                'image' => 'https://images.unsplash.com/photo-1556125574-d7f27ecbbb4e?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Stock tracking, suppliers, purchase orders, and alerts.',
                'link' => '#',
                'tags' => ['Laravel', 'PostgreSQL', 'Tailwind'],
                'seo_title' => 'Inventory Management',
                'seo_description' => 'Inventory and purchase order management.',
                'seo_keywords' => 'inventory, stock, erp',
                'focus_keyword' => 'Inventory',
            ],
            [
                'title' => 'Learning Management System (LMS)',
                'category' => 'Education',
                'image' => 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Courses, lessons, quizzes, certificates.',
                'link' => '#',
                'tags' => ['Laravel', 'Livewire', 'Tailwind'],
                'seo_title' => 'LMS Platform',
                'seo_description' => 'Online learning management with quizzes and certificates.',
                'seo_keywords' => 'lms, courses, education',
                'focus_keyword' => 'LMS',
            ],
            [
                'title' => 'Food Delivery App',
                'category' => 'Delivery',
                'image' => 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Restaurants, menus, cart, live order tracking.',
                'link' => '#',
                'tags' => ['Laravel', 'Pusher', 'Tailwind'],
                'seo_title' => 'Food Delivery',
                'seo_description' => 'Food delivery platform with live tracking.',
                'seo_keywords' => 'delivery, food, ordering',
                'focus_keyword' => 'Food Delivery',
            ],
            [
                'title' => 'Ride Sharing Platform',
                'category' => 'Mobility',
                'image' => 'https://images.unsplash.com/photo-1541447271466-1f0a2d188a12?auto=format&fit=crop&w=1200&q=80',
                'description' => 'Driver and rider matching, trip tracking, payments.',
                'link' => '#',
                'tags' => ['Laravel', 'Maps API', 'Stripe'],
                'seo_title' => 'Ride Sharing',
                'seo_description' => 'Ride sharing with real-time tracking and payments.',
                'seo_keywords' => 'rideshare, mobility, maps',
                'focus_keyword' => 'Ride Sharing',
            ],
            [
                'title' => 'Fintech Analytics Dashboard',
                'category' => 'Fintech',
                'image' => 'https://images.unsplash.com/photo-1551281044-8f8d15ee4b6a?auto=format&fit=crop&w=1200&q=80',
                'description' => 'KPIs, charts, and transaction insights for fintech teams.',
                'link' => '#',
                'tags' => ['Laravel', 'Chart.js', 'Tailwind'],
                'seo_title' => 'Fintech Dashboard',
                'seo_description' => 'Analytics dashboard for financial operations.',
                'seo_keywords' => 'fintech, analytics, dashboard',
                'focus_keyword' => 'Fintech Dashboard',
            ],
        ];

        foreach ($items as $i) {
            $slug = Str::slug($i['title']);
            if (!Project::where('slug', $slug)->exists()) {
                Project::create([
                    'title' => $i['title'],
                    'slug' => $slug,
                    'category' => $i['category'],
                    'image' => $i['image'],
                    'description' => $i['description'],
                    'link' => $i['link'],
                    'tags' => $i['tags'],
                    'seo_title' => $i['seo_title'],
                    'seo_description' => $i['seo_description'],
                    'seo_keywords' => $i['seo_keywords'],
                    'focus_keyword' => $i['focus_keyword'],
                ]);
            }
        }
    }
}
